### ISSUE TITLE
Hidden FAQ anchors

### ISSUE THREAD

**Issue by stevepeak** [asyncy/docs.asyncy.com#22]
When navigating the FAQ; click on a question and it jumps to the question but hides the question in the toolbar.

![screen recording 2018-11-08 at 10 52](https://user-images.githubusercontent.com/2041757/48194246-649b9800-e344-11e8-94bd-9da66f6e0115.gif)

**Comment by JeanBarriere** [comment]
Issue closed after resolution in PR #24
